### ISSUE TITLE
Templates not updated in super dev mode

### ISSUE THREAD

**Issue by anbuck** [hal/elemento#51]
If I make a change to a template while running in super dev mode, I have to restart the super dev mode server to get the updated template to take effect. Is there any way to make the templates update automatically when I refresh the page using super dev mode, just like code changes update automatically without restarting the server?

**Comment by vegegoku** [comment]
I am using elemento i dont face this issue, but you should know that since annotation processor are not triggered when a resource is changed and only work with the java sources, after you update the template you have to touch the corresponding java class in order to trigger the annotation processor and apply the new changes.

**Comment by anbuck** [comment]
@vegegoku When you say that you don't face the issue, do you mean that when you change your template file and touch the corresponding java class, super dev mode correctly updates it? Or do you mean that you don't face the issue because you don't use templates?

Thanks for the suggestion about having to touch the corresponding java class, but I have tried that the template still doesn't get updated. The issue seems to be that the annotation processor isn't run as part of the re-compilation in super dev mode. Is there some way to change that?

**Comment by vegegoku** [comment]
@anbuck I do use templates but looking again at your issue, i dont face the issue because i put the templates in the resources folder instead of sources folder. so as long as they are in the resources folder touching the java file should be enough.
sorry i should have read your comments more carefully.

**Comment by anbuck** [comment]
Interesting, thanks for the clarification. I have my templates in the resources folder too, so I'm not sure what would be different on my end.

**Comment by mseele** [comment]
@anbuck i doe use templates, work with _super dev mode_ and have the html files in the source folder. Touching the java files will re-generate the generated java files and _super dev mode_ works as expected

**Comment by anbuck** [comment]
Sounds good. Sorry, I forgot that was still open.
