### ISSUE TITLE
[Feature Request] Add "onAttach" helper method

### ISSUE THREAD

**Issue by mseele** [hal/elemento#59]
Comming from gwt widgets something i hardly miss is the "onAttached/Detached" functionality gwt widgets provides to the developer:  You can override to get notified when the widget is added/removed to the dom.

We need this to, e.g. focus and select input when it's attached, initialize [Split.js](https://github.com/nathancahill/Split.js), ...

This i something that would fit perfect into the `org.jboss.gwt.elemento.core.Elements` class. 
Here's the code i've wrote for onAttach:

```
private static String UID_KEY = "onattach-uid"; //$NON-NLS-1$

/**
 * Utility method to listen when a element is attached to the dom
 * 
 * @param element
 *            the element to listen for
 * @param callback
 *            will be called when the element has been attached to the dom
 */
public static void onAttach(HTMLElement element, Consumer<HTMLElement> callback) {
	String uid = Elements.createDocumentUniqueId();
	element.setAttribute(UID_KEY, uid);
	MutationObserver observer = new MutationObserver((records, o) -> {
		for (MutationRecord record : records) {
			if (record.addedNodes != null && record.addedNodes.length > 0) {
				if (DomGlobal.document.body.querySelector("[" + UID_KEY + "='" + uid + "']") != null) { //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
					element.removeAttribute(UID_KEY);
					o.disconnect();
					callback.accept(element);
				}
			}
		}
		return null;
	});
	MutationObserverInit ops = MutationObserverInit.create();
	ops.setChildList(true);
	ops.setSubtree(true);
	observer.observe(DomGlobal.document.body, ops);
}
```

**Comment by hpehl** [comment]
Looks good to me. Do you already use it in production? Is it performant?

**Comment by mseele** [comment]
Richtig now in development branch. For us its speedy, but we do not have
thousands of elements at the time of our current usage.

**Comment by vegegoku** [comment]
I have this implemented in in domino-ui here
https://github.com/DominoKit/domino-ui/blob/master/src/main/java/org/dominokit/domino/ui/utils/BodyObserver.java

you can use it like this :
```java
BodyObserver.observeAppend(targetElement, mutationRecord -> DomGlobal.console.info("element added"));

BodyObserver.observeRemoval(targetElement, mutationRecord -> DomGlobal.console.info("element removed"));
```
> methods could be renamed to `onAttach` and `onDetached`.

in my implementation it is the other way around where i attach only observer on the body and keep it alive instead of having multiple observers for each element, this reduce the need to loop over the mutation records for only once instead of looping for each observer.

also the implementation takes care of removing the observe listeners after the element is added or removed.

still i found cases mutation observer might not work, for example if i have **elementA** and **elementB**
assume i created an observer for **elementB**, then:
if i first append **elementA** to the body then appended **elementB** to **elementA** the callback will be invoked.
if i first append **elementB** to **elementA** then appended **elementA** to the body the callback wont be called.

because the mutation records will only have the root element in the list but will not list its children.
one way to solve this issue is to also loop over the children of the node in the mutation record, but this might reduce the performance.

the solution from @mseele solves this issue, and i am going to borrow this and merge it into mine.

:+1:

**Comment by hpehl** [comment]
@vegegoku Sound good to me. I agree renaming the methods to `onAttach()` and `onDetach()`. I'd like to move the public methods / callbacks to class `Elements` and keep the `BodyObserver` package private.

**Comment by vegegoku** [comment]
@hpehl i am doing some enhancements from @mseele solution, so i want to do some testing before we conclude this. ill post it here when i am done then we can agree on a PR for this.

**Comment by mseele** [comment]
@vegegoku great PR! You're solution is ways better than my short snippet we use 👍 I've commented on the PR to maybe improve a few things.

**Comment by hpehl** [comment]
Fixed by https://github.com/hal/elemento/pull/60
