### ISSUE TITLE
APT Processors (for templates) don't work well in Eclipse

### ISSUE THREAD

**Issue by cristian-spiescu** [hal/elemento#70]
Hi!

I'm just getting started w/ this awesome project. Although I don't plan to use primarily the templates feature, some colleagues of mine might use it, as they prefer the readability of a HTML vs DSL.

When importing a project (e.g. `sample/gin`) in Eclipse, it won't work out of the box. After a clean + build, there are compile errors because of the processor. E.g. for `ApplicationElement.java` = `Unable to read template "org/jboss/gwt/elemento/sample/gin/client/Todo.html": Java Model Exception: Core Exception [code 368] Resource '/gin/target/classes/org/jboss/gwt/elemento/sample/gin/client/Todo.html' does not exist.`.

When I look there, `Todo.html` does exist. But it was probably copied during the compile phase, and probably `ApplicationElement.java` was compiled (thus processor invoked) before. So maybe at that time the file didn't exist.

The work around: go to `ApplicationElement.java`, modify something meaningless => incremental build only on this file => error gone. However, a full clean + build will lead to the initial situation.

My question: are there users that successfully use the template processors in Eclipse? If yes, then somehow there is something wrong w/ my setup. If no => the processor may need to be adapted for use in Eclipse. I assume that it works correctly during a maven build.

I have experience w/ processors and APT. And there are many compatibility issues between execution within maven and within Eclipse. Some of them due to the incremental approach of Eclipse, but the majority due to the fact that "illegal" operations are done from within processors. Normally, a processor should only output content based on the content of the annotated file. In this case, the content is based on the `*.html` file, which is something that's not officially supported by the APT API.

Cheers!
Cristian

**Comment by anbuck-cardea** [comment]
Getting the template processor to regenerate based on only a change to the HTML template has been one of the main challenges for me using this library. I use gradle instead of maven and my solution was to write a gradle script that gets run at compile time that checks to see if the HTML template file has been modified since the corresponding templated java file was last generated. If so, I delete the java file to force it to be regenerated. This works well except that it still doesn't solve the problem that when running in super dev mode, if only an HTML file changes, GWT doesn't recognize that the project needs to be recompiled, so I have to manually do it from the command line before the site will update.

If anyone has an idea about how to get super dev mode to recognize changes to the HTML files, please let me know.

**Comment by anbuck** [comment]
Getting the template processor to regenerate based on only a change to the HTML template has been one of the main challenges for me using this library. I use gradle instead of maven and my solution was to write a gradle script that gets run at compile time that checks to see if the HTML template file has been modified since the corresponding templated java file was last generated. If so, I delete the java file to force it to be regenerated. This works well except that it still doesn't solve the problem that when running in super dev mode, if only an HTML file changes, GWT doesn't recognize that the project needs to be recompiled, so I have to manually do it from the command line before the site will update.

If anyone has an idea about how to get super dev mode to recognize changes to the HTML files, please let me know.

**Comment by r0bnewt0n** [comment]
I use maven and eclipse.  The problem you mention occurs when you update the project using Maven Update, or you do a Project->Clean, or you initially import the project into eclipse.

When I do one of those 3 things, in eclipse I run a "mvn clean compile" -- that gets the templates compiled.

Then, if I update a template class file, eclipse runs the annotion processor as usual and it works fine.  

And if I update the template html file then I need to "touch" the corresponding class file for the changes to take effect -- which is a slight hassle, but the benefit of using elemento templates outweighs this inconvenience.

**Comment by FrankHossfeld** [comment]
@cristian-spiescu Regarding the migrated GWT modules we will see a lot more processors, which replace the 'old' generators. ClientBundle, UiBinder, I18N, all of them will have none java files which will be processed by a processor.

Eclipse is well know for the bad handling of Maven and APT. The JIT-compile is nice, but does not work well with APT. And, I am pretty sure, that changing something in Spring Boot will also need a restart of the server.

**Comment by shincoding** [comment]
Hi, I came across this issue as well for the past few months.
@cristian-spiescu thank you for the suggestion. I made it work for now by:
1) Adding this plugin to pom file:
`  <plugin> 
       <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>add-source</goal>
                    </goals>
                    <configuration>
                        <sources>
                            <source>src/main/generated</source>
                        </sources>
                    </configuration>
                </execution>
            </executions>
   </plugin> `

**Comment by shincoding** [comment]
Hi, I came across this issue as well for the past few months.
@cristian-spiescu thank you for the suggestion. I made it work for now by:

Adding this plugin to pom file:
<plugin> <groupId>org.codehaus.mojo</groupId> <artifactId>build-helper-maven-plugin</artifactId> <executions> <execution> <phase>generate-sources</phase> <goals> <goal>add-source</goal> </goals> <configuration> <sources> <source>src/main/generated</source> </sources> </configuration> </execution> </executions> </plugin>

**Comment by shincoding** [comment]
Hi, I came across this issue as well for the past few months.
@cristian-spiescu thank you for the suggestion. I made it work for now by:

1) Adding this plugin to pom file:
```
<plugin> 
    <groupId>org.codehaus.mojo</groupId> 
    <artifactId>build-helper-maven-plugin</artifactId> 
    <executions> 
        <execution> 
            <phase>generate-sources</phase> 
            <goals>
                <goal>add-source</goal>
            </goals>
           <configuration>
                 <sources> <source>src/main/template</source> </sources>
          </configuration>
       </execution>
   </executions>
</plugin>
```
2) Adding the plugin for resources
```
<plugin>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.1.0</version>
    <configuration>
        <resources>
            <resource>
                <directory>src/main/template</directory>
            </resource>
         </resources>
     </configuration>
</plugin>
```
After adding the template files to src/main/template, it should work on Maven Update / Project -> Clean.

In my previous attempts, instead of using maven-resources-plugin, I used the `<resources>` tag like:
```
<resources>
    <resource>
        <resource>
            <directory>src/main/template</directory>
        </resource>
</resources>
```
This works on maven compile, but fails on Maven Update because it modifies the Java Build Path to only include "**/*.java" type files in templates folder. Adding `<includes>` tag did not make a change it either.

According to this post: https://stackoverflow.com/questions/11896742/what-is-the-difference-between-maven-resources-plugin-and-the-project-build-reso#targetText=1%20Answer&targetText=The%20maven%2Dresources%2Dplugin%20is,in%20your%20pom.xml%20file.&targetText=Furthermore%20the%20resources%20goal%20of,the%20maven%2Dresources%2Dplugin.
the only difference between `<resources>` and maven-resources-plugin, is the Maven goal. So since Maven Update has a different build lifecycle (https://stackoverflow.com/questions/42554213/what-exactly-does-maven-update-project-do-in-eclipse), I believe Maven Update doesn't trigger the plugin in the same way it triggers `<resources>` tag content. However, I wasn't able to verify, and would appreciate any explanation of this.

**Comment by cristian-spiescu** [comment]
Thanks @shincoding for the detailed and well documented response. In the links you posted, I found the answer regarding an old Maven/Eclipse integration question that was puzzling me.

Very clever! The `maven-resources-plugin` is one (of the few IMO) plugins that get executed during an Eclipse build. So before the compilation, this plugin will move the template files in `/target` and then during compilation / APT invocation, the processor will be happy to find them there.

I don't know if the team of this project has time for a modification of the code source in the processors, cf. this issue. But maybe this explanation may be copied somewhere in the wiki section meanwhile?

**Comment by cristian-spiescu** [comment]
I have just tested the above proposed solution. And I was wondering why this works vs. the initial setup, w/ the template file inside `src/main/resources`. 

And I think I discovered an even simpler solution: put the template file directly in `src/main/java`.

**Comment by hpehl** [comment]
I'm closing this with the release of Elemento 1.0.0 and templates moved to crysknife.
